version: '3.7'

services:

  blackbox:
    image: prom/blackbox-exporter
    volumes:
      - ./exporters/blackbox/blackbox.yml:/etc/blackbox_exporter/config.yml
    networks: 
      - "metrics-network"
    expose: 
      - "9115"

  prom:
    image: prom/prometheus:v2.27.1
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/blackbox_targets.json:/etc/prometheus/blackbox_targets.json
      - ./prometheus/node_targets.json:/etc/prometheus/node_targets.json
    networks: 
      - "metrics-network"
    expose: 
      - "9090"
    ports:
        - "9090:9090"

  grafana:
    image: grafana/grafana-oss
    volumes:
      - ./grafana/storage:/var/lib/grafana
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
    user: '0'
    ports:
        - "3000:3000"
    networks: 
      - "metrics-network"
    expose: 
      - "3000"
    environment:
      VIRTUAL_PORT: 3000
      VIRTUAL_HOST: status.wearehorizontal.org
      LETSENCRYPT_HOST: status.wearehorizontal.org


  nginx:
    image: "jwilder/nginx-proxy:latest"
    container_name: "nginx"
    volumes:
        - "html:/usr/share/nginx/html"
        - "dhparam:/etc/nginx/dhparam"
        - "vhost:/etc/nginx/vhost.d"
        - "certs:/etc/nginx/certs"
        - "htpasswd:/srv/docker/nginx/htpasswd/"
        - "./nginx-config/proxy_custom_config.conf:/etc/nginx/conf.d/proxy_custom_config.conf:ro"
        - "/run/docker.sock:/tmp/docker.sock:ro"
    restart: "always"
    networks: 
        - "metrics-network"
    ports:
        - "80:80"
        - "443:443"
        
  letsencrypt:
    image: "jrcs/letsencrypt-nginx-proxy-companion:latest"
    container_name: "letsencrypt-helper"
    volumes:
        - "html:/usr/share/nginx/html"
        - "dhparam:/etc/nginx/dhparam"
        - "vhost:/etc/nginx/vhost.d"
        - "certs:/etc/nginx/certs"
        - "/run/docker.sock:/var/run/docker.sock:ro"
    environment:
        NGINX_PROXY_CONTAINER: "nginx"
        DEFAULT_EMAIL: "user@domain.com"
    restart: "always"
    depends_on:
        - "nginx"
    networks: 
        - "metrics-network"

volumes:
  certs:
  html:
  vhost:
  dhparam:
  htpasswd:
  
networks:
  metrics-network:
    external: true
