version: '3.7'

services:

  blackbox:
    image: prom/blackbox-exporter
    ports:
      - 9115:9115
    volumes:
      - ./prometheus/exporters/blackbox/blackbox.yml:/etc/blackbox_exporter/config.yml
    networks: 
        - "metrics-network"
    expose: 
      - "9115"

  prom:
    image: prom/prometheus:v2.27.1
    ports:
      - 9090:9090
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks: 
        - "metrics-network"
    expose: 
      - "9090"

  grafana:
    image: grafana/grafana-oss
    ports:
      - 3000:3000
    volumes:
      - ./grafana/storage:/var/lib/grafana
    user: '0'
    networks: 
    - "metrics-network"
    expose: 
      - "3000"


networks:
  metrics-network:
    external: true
