# my global config
global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: "prometheus"

    static_configs:
      - targets: ["localhost:9090"]

  - job_name: 'node_exporter_metrics'
    scrape_interval: 5s
    static_configs:
      - targets: ['37.218.244.11:9100'] # beta tellaweb
        labels:
          instance: 'beta.web.tella-app.org'
      - targets: ['37.218.242.65:9100'] # mattermost chat 
        labels:
          instance: 'chat.wearehorizontal.org'

  - job_name: 'cadvisor_metrics'
    scrape_interval: 5s
    static_configs:
      - targets: ['37.218.242.65:9001'] # mattermost chat 
        labels:
          instance: 'chat.wearehorizontal.org'

  - job_name: blackbox # To get metrics about the exporter’s targets
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - https://wearehorizontal.org
        - https://tella-app.org
        - https://admin.tella-app.org
        - https://collect.tella-app.org
        - https://form.tella-app.org
        - https://collect.essc.cleen.org
        - https://form.essc.cleen.org
        - https://admin.essc.cleen.org
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox:9115